name: Run Ansible Playbook

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH setup
        shell: bash
        run: |
          eval $(ssh-agent -s)
          mkdir -p /home/runner/.ssh
          echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa

          # Add all hosts to known_hosts
          hosts=("35.238.96.106" "34.71.102.253")
          for host in "${hosts[@]}"; do
            ssh-keyscan -t rsa,dsa,ecdsa,ed25519 $host >> /home/runner/.ssh/known_hosts
          done

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Check SSH Connection
        shell: bash
        run: |
          hosts=("35.238.96.106" "192.168.1.2" "example.com")
          for host in "${hosts[@]}"; do
            ssh -vvv -o StrictHostKeyChecking=no -i /home/runner/.ssh/id_rsa ${{ secrets.ANSIBLE_USER }}@$host "echo 'SSH connection successful to $host'"
          done

      - name: Run Ansible Playbook
        shell: bash
        run: |
          ansible-playbook -vvvv --private-key /home/runner/.ssh/id_rsa -u ${{ secrets.ANSIBLE_USER }} -i inventory.yml playbook.yml
